
title: Resume - Ankit Aich (FullStack Developer)
url: 'https://ankitaich09.github.io'
baseurl: '/resume' #change it according to your repository name


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6


#Profile information
name: Pradyumna Chatterjee
tagline: Full Stack Developer (Python & Java)
pic: user.jpg  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below.

#sidebar links
email: xxxxxxxxxx.xxx@gmail.com (Please request below for contact details)
phone: xxxx-xx-xxxx (Please request below for contact details)
website: pradyumnac.github.io #do not add http://
linkedin: 'pradyumnac'
github: 'pradyumnac'
twitter: '@pradyumnacster'


# Tracker
# analytics: 
#Update all the sections by editing the files inside _includes folder.
