
title: Resume - Ankit Aich (AI and NLP researcher)
url: 'https://ankitaich09.github.io'
baseurl: '/resume' #change it according to your repository name


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6


#Profile information
name: Ankit Aich
tagline: Artificial Intelligence and NLP researcher.
pic: ankit.jpg  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below.

#sidebar links
email: gre.ankit09@gmail.com 
phone: 9051114223, 8420493641
website: 
linkedin: 
github: 
twitter: 


# Tracker
# analytics: 
#Update all the sections by editing the files inside _includes folder.
